In [1]:
import pandas as pd
df = pd.read_csv('dns.csv', encoding = "ISO-8859-1")

In [2]:
df.head()

,QR,OPCODE,QNAME,QTYPE,QCLS,RRNAME,RRTYPE,RCLS,TTL,RLEN,RDATA,AA,ID,QDCNT,ANCNT,NSCNT,ARCNT
0,0,0,planetlab2.isi.jhu.edu,1.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,0,41945,1,0,0,1
1,1,0,planetlab2.isi.jhu.edu,1.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,1,41945,1,0,1,1
2,0,0,planetlab2.isi.jhu.edu,1.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,0,25281,1,0,0,1
3,1,0,planetlab2.isi.jhu.edu,1.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,1,25281,1,0,1,1
4,0,0,dns2.isi.jhu.edu,255.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,0,9882,1,0,0,0

In [3]:
df.count()

QR        404198
OPCODE    404198
QNAME     404145
QTYPE     404196
QCLS      404196
RRNAME    166284
RRTYPE    166284
RCLS      166284
TTL       166284
RLEN      166284
RDATA     165740
AA        404198
ID        404198
QDCNT     404198
ANCNT     404198
NSCNT     404198
ARCNT     404198
dtype: int64

In [4]:
df.tail()

,QR,OPCODE,QNAME,QTYPE,QCLS,RRNAME,RRTYPE,RCLS,TTL,RLEN,RDATA,AA,ID,QDCNT,ANCNT,NSCNT,ARCNT
404193,1,0,www.weather.com,1.0,1.0,www.weather.com,5.0,1.0,60.0,33.0,pmd-wwwweathercomedgekeynet,0,27818,1,3,0,0
404194,0,0,textsecure-service-ca.whispersystems.org,1.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,0,540,1,0,0,0
404195,0,0,textsecure-service-ca.whispersystems.org,1.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,0,32517,1,0,0,1
404196,1,0,textsecure-service-ca.whispersystems.org,1.0,1.0,textsecure-service-ca.whispersystems.org,1.0,1.0,60.0,4.0,6ìvÿ,0,32517,1,1,0,1
404197,1,0,textsecure-service-ca.whispersystems.org,1.0,1.0,textsecure-service-ca.whispersystems.org,1.0,1.0,60.0,4.0,6ìvÿ,0,540,1,1,0,0

In [5]:
u = df['QNAME'].dropna().unique()

In [6]:
len(u)

11226

In [12]:
u = list(u)
dblclk = [url for url in u if 'doubleclick' in url]

In [13]:
len(dblclk)

41

In [14]:
dblclk

['googleads.g.doubleclick.net',
 'pagead46.l.doubleclick.net',
 'stats.g.doubleclick.net',
 'stats.l.doubleclick.net',
 'cm.g.doubleclick.net',
 'pagead.l.doubleclick.net',
 '1873234.fls.doubleclick.net',
 'dart.l.doubleclick.net',
 'pubads.g.doubleclick.net',
 'partnerad.l.doubleclick.net',
 'googleads4.g.doubleclick.net',
 'adx.g.doubleclick.net',
 'static-doubleclick-net.l.google.com',
 'ad.doubleclick.net',
 '5352434.fls.doubleclick.net',
 '5485101.fls.doubleclick.net',
 'static.doubleclick.net',
 '2542116.fls.doubleclick.net',
 '2895566.fls.doubleclick.net',
 'survey.g.doubleclick.net',
 '4267185.fls.doubleclick.net',
 'ads-bid.l.doubleclick.net',
 '5451642.fls.doubleclick.net',
 'fls.doubleclick.net',
 '621119.fls.doubleclick.net',
 '4606132.fls.doubleclick.net',
 '2810449.fls.doubleclick.net',
 '3721446.fls.doubleclick.net',
 'adclick.g.doubleclick.net',
 'securepubads.g.doubleclick.net',
 'bid.g.doubleclick.net',
 '4954221.fls.doubleclick.net',
 '4968236.fls.doubleclick.net',
 '4704202.fls.doubleclick.net',
 '3973258.fls.doubleclick.net',
 '1620481.fls.doubleclick.net',
 '2566600.fls.doubleclick.net',
 '4735610.fls.doubleclick.net',
 '5290727.fls.doubleclick.net',
 '3951336.fls.doubleclick.net',
 '4053494.fls.doubleclick.net']

In [15]:
gst = [url for url in u if 'gstatic' in url]
len(gst)

72

In [16]:
gst

['ssl.gstatic.com',
 'csi.gstatic.com',
 'www.gstatic.com',
 'fonts.gstatic.com',
 'gstaticadssl.l.google.com',
 'p4-aji4t2yf67rpk-hhlwzgmtrxuupt74-if-v6exp3-v4.metric.gstatic.com',
 'p4-bmsnwhyuzcaqu-lig3i6cqrn2vjqvn-if-v6exp3-v4.metric.gstatic.com',
 'p4-bmsnwhyuzcaqu-lig3i6cqrn2vjqvn-105877-i2.stbcast.metric.gstatic.com',
 'p4-bmsnwhyuzcaqu-lig3i6cqrn2vjqvn-105877-i1.unicast.metric.gstatic.com',
 'p4-bmsnwhyuzcaqu-lig3i6cqrn2vjqvn-105877-s1-v6exp3-v4.metric.gstatic.com',
 'maps.gstatic.com',
 'p2-futwawktmmp24-e555y3fdnj5fcyf2-if-v6exp3-v4.metric.gstatic.com',
 'p2-futwawktmmp24-e555y3fdnj5fcyf2-273571-i1-v6exp3-v4.metric.gstatic.com',
 'p2-futwawktmmp24-e555y3fdnj5fcyf2-273571-i2-v6exp3-ds.metric.gstatic.com',
 'p2-futwawktmmp24-e555y3fdnj5fcyf2-273571-s1-v6exp3-v4.metric.gstatic.com',
 'encrypted-tbn1.gstatic.com',
 'encrypted-tbn3.gstatic.com',
 'encrypted-tbn2.gstatic.com',
 'encrypted-tbn0.gstatic.com',
 'p4-beignbudgtavg-inrzcs52mhhk2vy4-if-v6exp3-v4.metric.gstatic.com',
 'p4-gciejiw42p2tu-yjxptfessjyao6ul-if-v6exp3-v4.metric.gstatic.com',
 'p4-gciejiw42p2tu-yjxptfessjyao6ul-342107-i2-v6exp3-ds.metric.gstatic.com',
 'p4-gciejiw42p2tu-yjxptfessjyao6ul-342107-i1-v6exp3-v4.metric.gstatic.com',
 'p4-gciejiw42p2tu-yjxptfessjyao6ul-342107-s1-v6exp3-v4.metric.gstatic.com',
 't3.gstatic.com',
 't2.gstatic.com',
 't1.gstatic.com',
 't0.gstatic.com',
 '80dcfbe4-oxug5cld2mrjnmfi-c2r-ds.metric.gstatic.com',
 'p4-crbejroelge2u-jyea6t3nx2mgbc73-if-v6exp3-v4.metric.gstatic.com',
 'p4-crbejroelge2u-jyea6t3nx2mgbc73-125721-i1-v6exp3-v4.metric.gstatic.com',
 'p4-crbejroelge2u-jyea6t3nx2mgbc73-125721-i2-v6exp3-ds.metric.gstatic.com',
 'p4-crbejroelge2u-jyea6t3nx2mgbc73-125721-s1-v6exp3-v4.metric.gstatic.com',
 'p4-cx363zjym6gqm-ek47z6aswkggdy5n-if-v6exp3-v4.metric.gstatic.com',
 'p4-cx363zjym6gqm-ek47z6aswkggdy5n-785192-i1-v6exp3-ds.metric.gstatic.com',
 'p4-cx363zjym6gqm-ek47z6aswkggdy5n-785192-i2-v6exp3-v4.metric.gstatic.com',
 'p4-cx363zjym6gqm-ek47z6aswkggdy5n-785192-s1-v6exp3-v4.metric.gstatic.com',
 'p4-dd7rn7ccqa24o-tqgpapjl6rhjjmzf-if-v6exp3-v4.metric.gstatic.com',
 'p4-e4wy2mfcnngqa-vtibu3aem4pn3j3s-if-v6exp3-v4.metric.gstatic.com',
 'p4-fkixnq552mg7q-fikzrgdqkfwnsw5u-if-v6exp3-v4.metric.gstatic.com',
 'p4-fkixnq552mg7q-fikzrgdqkfwnsw5u-831591-i1-v6exp3-v4.metric.gstatic.com',
 'p4-fkixnq552mg7q-fikzrgdqkfwnsw5u-831591-i2-v6exp3-ds.metric.gstatic.com',
 'p4-fkixnq552mg7q-fikzrgdqkfwnsw5u-831591-s1-v6exp3-v4.metric.gstatic.com',
 'p4-gf7y32uup25vu-t7dwhckvdmskocas-if-v6exp3-v4.metric.gstatic.com',
 'p4-akavg23hcirck-uj5hfrndalcpq4ku-if-v6exp3-v4.metric.gstatic.com',
 'p4-gf7y32uup25vu-t7dwhckvdmskocas-618723-i2-v6exp3-ds.metric.gstatic.com',
 'p4-gf7y32uup25vu-t7dwhckvdmskocas-618723-i1-v6exp3-v4.metric.gstatic.com',
 'p4-akavg23hcirck-uj5hfrndalcpq4ku-773369-i1-v6exp3-v4.metric.gstatic.com',
 'p4-akavg23hcirck-uj5hfrndalcpq4ku-773369-i2-v6exp3-ds.metric.gstatic.com',
 'p4-gf7y32uup25vu-t7dwhckvdmskocas-618723-s1-v6exp3-v4.metric.gstatic.com',
 'p4-akavg23hcirck-uj5hfrndalcpq4ku-773369-s1-v6exp3-v4.metric.gstatic.com',
 'p2-mu4f75m45bhr6-344mkggtttgbiqoo-if-v6exp3-v4.metric.gstatic.com',
 'p2-mu4f75m45bhr6-344mkggtttgbiqoo-949440-i1-v6exp3-ds.metric.gstatic.com',
 'p2-mu4f75m45bhr6-344mkggtttgbiqoo-949440-i2-v6exp3-v4.metric.gstatic.com',
 'p2-mu4f75m45bhr6-344mkggtttgbiqoo-949440-s1-v6exp3-v4.metric.gstatic.com',
 'p2-pilhoy6vhda6w-zveh2e3kkztanp6y-if-v6exp3-v4.metric.gstatic.com',
 'p2-pilhoy6vhda6w-zveh2e3kkztanp6y-977760-i1-v6exp3-ds.metric.gstatic.com',
 'p2-pilhoy6vhda6w-zveh2e3kkztanp6y-977760-i2-v6exp3-v4.metric.gstatic.com',
 'p4-fcxf3kd4kt4tw-v44445rfc5nofn7u-if-v6exp3-v4.metric.gstatic.com',
 'p4-fcxf3kd4kt4tw-v44445rfc5nofn7u-386234-i1-v6exp3-ds.metric.gstatic.com',
 'p4-fcxf3kd4kt4tw-v44445rfc5nofn7u-386234-i2-v6exp3-v4.metric.gstatic.com',
 'p4-fcxf3kd4kt4tw-v44445rfc5nofn7u-386234-s1-v6exp3-v4.metric.gstatic.com',
 'p4-dt3onovxodbgu-jkidnfu7fcnosxeb-if-v6exp3-v4.metric.gstatic.com',
 'p4-bctflmq554s7s-sq45zioycnpvpyqz-if-v6exp3-v4.metric.gstatic.com',
 'p4-flrehx5oeowgg-bfiadbnc5zlfilot-if-v6exp3-v4.metric.gstatic.com',
 'p4-fouk4n3p5fzj6-xkpakxbjtgyd6xvn-if-v6exp3-v4.metric.gstatic.com',
 'p4-fygjjtz7zgrv2-b3lkif4iffxi35b6-if-v6exp3-v4.metric.gstatic.com',
 'p4-gnocth4b6fpjk-ih66dz7rkfokfgat-if-v6exp3-v4.metric.gstatic.com',
 'p2-cqxlta7ubelkw-l3cxc4m37rnhwksb-if-v6exp3-v4.metric.gstatic.com',
 'p2-cqxlta7ubelkw-l3cxc4m37rnhwksb-120548-i2-v6exp3-v4.metric.gstatic.com',
 'p2-cqxlta7ubelkw-l3cxc4m37rnhwksb-120548-i1-v6exp3-ds.metric.gstatic.com',
 'p2-cqxlta7ubelkw-l3cxc4m37rnhwksb-120548-s1-v6exp3-v4.metric.gstatic.com']

In [24]:
#df['poop'] = df['RRNAME'].dropna()
#df['poop'].map(lambda x: x.upper())
df1 = df.dropna()

In [25]:
df1.head()

,QR,OPCODE,QNAME,QTYPE,QCLS,RRNAME,RRTYPE,RCLS,TTL,RLEN,RDATA,AA,ID,QDCNT,ANCNT,NSCNT,ARCNT,poop
5,1,0,dns2.isi.jhu.edu,255.0,1.0,dns2.isi.jhu.edu,1.0,1.0,3600.0,4.0,Ü÷þ,1,9882,1,1,2,1,dns2.isi.jhu.edu
7,1,0,isi.jhu.edu,1.0,1.0,isi.jhu.edu,1.0,1.0,3600.0,4.0,Ü÷,1,33418,1,1,2,3,isi.jhu.edu
11,1,0,isi.jhu.edu,1.0,1.0,isi.jhu.edu,1.0,1.0,3600.0,4.0,Ü÷,1,63761,1,1,0,1,isi.jhu.edu
15,1,0,isi.jhu.edu,1.0,1.0,isi.jhu.edu,1.0,1.0,3600.0,4.0,Ü÷,1,21010,1,1,2,3,isi.jhu.edu
18,1,0,cds.c2z6c7z7.hwcdn.net,1.0,1.0,cds.c2z6c7z7.hwcdn.net,1.0,1.0,300.0,4.0,Í¹Ø\n,0,40941,1,2,0,1,cds.c2z6c7z7.hwcdn.net

In [26]:
df1['poop'].map(lambda x: x.upper())

5                                        DNS2.ISI.JHU.EDU
7                                             ISI.JHU.EDU
11                                            ISI.JHU.EDU
15                                            ISI.JHU.EDU
18                                 CDS.C2Z6C7Z7.HWCDN.NET
19                                 CDS.C2Z6C7Z7.HWCDN.NET
22                                      PLAY.L.GOOGLE.COM
23                                        PLAY.GOOGLE.COM
26               TEXTSECURE-SERVICE-CA.WHISPERSYSTEMS.ORG
27               TEXTSECURE-SERVICE-CA.WHISPERSYSTEMS.ORG
30                                    CLIENTS4.GOOGLE.COM
31                                    CLIENTS4.GOOGLE.COM
33                                            ISI.JHU.EDU
35                                            ISI.JHU.EDU
38                            STAR-MINI.C10R.FACEBOOK.COM
39                                       WWW.FACEBOOK.COM
41                                        PLAY.GOOGLE.COM
44                                 DL-DEBUG.X.DROPBOX.COM
45                                 DL-DEBUG.X.DROPBOX.COM
47                                 KINGFISHER.ISI.JHU.EDU
50                                  CLIENT-CF.DROPBOX.COM
51                                  CLIENT-CF.DROPBOX.COM
53                                            ISI.JHU.EDU
55                                            ISI.JHU.EDU
59                                       DNS1.ISI.JHU.EDU
61                                       DNS1.ISI.JHU.EDU
65                                        SSL.GSTATIC.COM
68                            STAR-MINI.C10R.FACEBOOK.COM
69                            STAR-MINI.C10R.FACEBOOK.COM
71                                            ISI.JHU.EDU
                               ...
404132                                    DOCS.GOOGLE.COM
404133                                    DOCS.GOOGLE.COM
404135                                        ISI.JHU.EDU
404138                          STATS-PUBLIC.GRAMMARLY.IO
404139                          STATS-PUBLIC.GRAMMARLY.IO
404143                                        ISI.JHU.EDU
404146    ASIMOV-WIN.VORTEX.DATA.MICROSOFT.COM.AKADNS.NET
404148           BN2.VORTEX.DATA.MICROSOFT.COM.AKADNS.NET
404149    ASIMOV-WIN.VORTEX.DATA.MICROSOFT.COM.AKADNS.NET
404151                                        ISI.JHU.EDU
404158                          SZHOME.MAIL.G.COMCAST.NET
404159                          SZHOME.MAIL.G.COMCAST.NET
404162         GEO.SETTINGS.DATA.MICROSOFT.COM.AKADNS.NET
404164         BN2.SETTINGS.DATA.MICROSOFT.COM.AKADNS.NET
404165         GEO.SETTINGS.DATA.MICROSOFT.COM.AKADNS.NET
404169                             KINGFISHER.ISI.JHU.EDU
404172                         SKYDOCS.SKYPROD.AKADNS.NET
404173                         SKYDOCS.SKYPROD.AKADNS.NET
404176                                      PBS.TWIMG.COM
404177                                      PBS.TWIMG.COM
404179                            SAFEBROWSING.GOOGLE.COM
404181                      SAFEBROWSING-CACHE.GOOGLE.COM
404184                        STAR-MINI.C10R.FACEBOOK.COM
404185                        STAR-MINI.C10R.FACEBOOK.COM
404187                                COURSES.ISI.JHU.EDU
404190                                    WWW.WEATHER.COM
404192                             E7121.G.AKAMAIEDGE.NET
404193                                    WWW.WEATHER.COM
404196           TEXTSECURE-SERVICE-CA.WHISPERSYSTEMS.ORG
404197           TEXTSECURE-SERVICE-CA.WHISPERSYSTEMS.ORG
Name: poop, dtype: object

In [28]:
df1['poo'] = df1['RRNAME']
df1['poo'] = df1['poo'].map(lambda x: x.upper())
df1.head()

/home/sean/class_code/capstone/capstone_code/experiment1/venv/lib/python3.5/site-packages/ipykernel/__main__.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  if __name__ == '__main__':
/home/sean/class_code/capstone/capstone_code/experiment1/venv/lib/python3.5/site-packages/ipykernel/__main__.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  from ipykernel import kernelapp as app

,QR,OPCODE,QNAME,QTYPE,QCLS,RRNAME,RRTYPE,RCLS,TTL,RLEN,RDATA,AA,ID,QDCNT,ANCNT,NSCNT,ARCNT,poop,poo
5,1,0,dns2.isi.jhu.edu,255.0,1.0,dns2.isi.jhu.edu,1.0,1.0,3600.0,4.0,Ü÷þ,1,9882,1,1,2,1,dns2.isi.jhu.edu,DNS2.ISI.JHU.EDU
7,1,0,isi.jhu.edu,1.0,1.0,isi.jhu.edu,1.0,1.0,3600.0,4.0,Ü÷,1,33418,1,1,2,3,isi.jhu.edu,ISI.JHU.EDU
11,1,0,isi.jhu.edu,1.0,1.0,isi.jhu.edu,1.0,1.0,3600.0,4.0,Ü÷,1,63761,1,1,0,1,isi.jhu.edu,ISI.JHU.EDU
15,1,0,isi.jhu.edu,1.0,1.0,isi.jhu.edu,1.0,1.0,3600.0,4.0,Ü÷,1,21010,1,1,2,3,isi.jhu.edu,ISI.JHU.EDU
18,1,0,cds.c2z6c7z7.hwcdn.net,1.0,1.0,cds.c2z6c7z7.hwcdn.net,1.0,1.0,300.0,4.0,Í¹Ø\n,0,40941,1,2,0,1,cds.c2z6c7z7.hwcdn.net,CDS.C2Z6C7Z7.HWCDN.NET